// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaOdontologica.API.Migrations
{
    [DbContext(typeof(ClinicaOdontologicaAPIContext))]
    partial class ClinicaOdontologicaAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCita"));

                    b.Property<int>("IdConsultorio")
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    b.Property<int>("IdOdontologo")
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("Idpaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciemte");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("fechaCita")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_cita");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCita");

                    b.HasIndex("IdConsultorio");

                    b.HasIndex("IdOdontologo");

                    b.HasIndex("Idpaciente");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Consultorio", b =>
                {
                    b.Property<int>("idConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idConsultorio"));

                    b.Property<string>("EquipamientoPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("numeroSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("piso")
                        .HasColumnType("integer");

                    b.HasKey("idConsultorio");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.DetalleCita", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<decimal>("costoAplicado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<int>("idTratamiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDetalle");

                    b.HasIndex("idCita");

                    b.HasIndex("idTratamiento");

                    b.ToTable("detallesCitas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Especialidad", b =>
                {
                    b.Property<int>("idEspeciliadad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEspeciliadad"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("nombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("idEspeciliadad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Factura", b =>
                {
                    b.Property<string>("IdFactura")
                        .HasColumnType("text")
                        .HasColumnName("id_factura");

                    b.Property<string>("estadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<decimal>("impuestos")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdFactura");

                    b.HasIndex("idCita");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.HistorialMedico", b =>
                {
                    b.Property<int>("IdHistorialMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historialMedico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorialMedico"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("alergias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alergias");

                    b.Property<string>("enfermedadesPrevias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("enfermedades_previas");

                    b.Property<string>("tipoSangre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("IdHistorialMedico");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Historialesmedicos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologo", b =>
                {
                    b.Property<int>("IdOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdontologo"));

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("registoMedico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registro_medico");

                    b.HasKey("IdOdontologo");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("Odontologos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPaciente"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly>("fechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("idPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Receta", b =>
                {
                    b.Property<int>("idRecetas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_recetas");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idRecetas"));

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("indicaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idRecetas");

                    b.HasIndex("idCita");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Tratamiento", b =>
                {
                    b.Property<int>("idTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTratamiento"));

                    b.Property<decimal>("costo")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_base");

                    b.Property<TimeOnly>("duracionEstimadaMinutos")
                        .HasColumnType("time without time zone")
                        .HasColumnName("Duracion_estimada_minutos");

                    b.Property<string>("nombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_tratamiento");

                    b.HasKey("idTratamiento");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Cita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Consultorio", "Consultorio")
                        .WithMany()
                        .HasForeignKey("IdConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Odontologo", "Odontologo")
                        .WithMany()
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("Idpaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.DetalleCita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("idTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Factura", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.HistorialMedico", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologo", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Receta", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });
#pragma warning restore 612, 618
        }
    }
}
